collections:
  - name: geerlingguy.php_roles
    version: 1.0.0
    source: https://galaxy.ansible.com
  - name: a10.acos_axapi
    version: 1.2.0
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
