collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: awx.awx
  - name: community.general
    version: 10.7.0
  - name: community.vmware
    version: "<5.0.0"
  - name: kubernetes.core
    version: 2.1.1
  - name: redhat.openshift
