---
- hosts: all
  gather_facts: false
  
  tasks:
   - name: Template a file to /etc/file.conf
     ansible.builtin.template:
       src: ../templates/krb5.conf.j2
       dest: /etc/krb5.conf
       owner: root
       group: root
       mode: '0644'
     delegate_to: localhost
    
   - name: Get whoami information
     ansible.windows.win_whoami:
