- name: Installing Windows Updates
  hosts: all

  tasks:
   - name: Windows Updates
     win_updates:
       category_names:
         - Application
         - CriticalUpdates
         - DefinitionUpdates
         - SecurityUpdates
     reboot: yes
