- name: Playbook to configure ansible controller post installation
  hosts: all
  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./vars
        extensions: ["yml"]
  roles:
    - infra.controller_configuration.job_templates
