---

- name: Deploy Ansible Tower Inventories
  ansible.tower.tower_inventory:
    name: "{{ item.key }}"
    description: "{{ item.value.description|default(item.key) }}" 
    organization: "{{ item.value.organization|default('Default') }}"
    tower_username: admin
    tower_password: "{{ ansible_tower_admin }}" 
    tower_host: "https://{{inventory_hostname}}/"
    tower_verify_ssl: False
  loop: "{{ ansible_tower_config[TIER].inventories|dict2items }}" 
  loop_control:
    label: "{{ item.key }}"

- name: Deploy general use localhost inventory
  ansible.tower.tower_host:
    name: localhost
    inventory: SCHRODERS_localhost_inventory
    tower_username: admin
    tower_password: "{{ ansible_tower_admin }}" 
    tower_host: "https://{{inventory_hostname}}/"
    tower_verify_ssl: False
    
- name: Deploy Ansible Tower Inventory sources
  ansible.tower.tower_inventory_source:
    name: "{{ item.key }}"
    description: "{{ item.value.description|default(item.key) }}" 
    credential: "{{ item.value.credential|default(omit) }}" # This is only required for external sources not based in projects.
    source: "{{ item.value.source|default('scm') }}" 
    source_project: "{{ item.value.source_project }}" 
    inventory: "{{ item.value.inventory }}" 
    source_path: "{{ item.value.source_path }}" 
    overwrite: "{{ item.value.overwrite|default(False) }}" 
    update_on_project_update: "{{ item.value.update_on_project_update|default(False) }}" 
    update_cache_timeout: "{{ item.value.update_cache_timeout|default(omit) }}" 
    overwrite_vars: "{{ item.value.overwrite_vars|default(False) }}" 
    update_on_launch: "{{ item.value.update_on_launch|default(False) }}" 
    tower_username: admin
    tower_password: "{{ ansible_tower_admin }}" 
    tower_host: "https://{{inventory_hostname}}/"
    tower_verify_ssl: False
  loop: "{{ ansible_tower_config[TIER].inventory_sources|dict2items }}" 
  loop_control:
    label: "{{ item.key }}"
    
