---
- name: create user from galaxy colletions
  hosts: all
 
  tasks:
  - name: using ansible.tower collections
    ansible.tower.tower_user:
      email: miles@gmail.com
      first_name: Miles
      last_name: Morales
      is_superuser: yes
      password: miles123
      username: milesmorales
      tower_host: 192.168.122.2
      tower_username: admin
      tower_password: alfonso123
