---
- name: Open port 10050 on Zabbix agent
  hosts: all
  
  tasks:
  - name: Permit incoming connections on port 10050/tcp
    ansible.posix.firewalld:
      port: 10050/tcp
      permanent: yes
      zone: public
      state: enabled
