---
controller_templates:
- name: Survey Template with vars
  job_type: run
  inventory: Demo Inventory
  execution_environment: default
  project: Demo Project
  playbook: helloworld.yml
  credentials:
  - Demo Credential
  verbosity: 0
