---
- name: Prueba de escalado
  hosts: all
  gather_facts: no

  tasks:
      community.general.sesu:
        shell: |
          id
        become: yes
        become_exe: sesu
        become_flags: "-"
        become_user: root
