- name: Get Host Names
  hosts: '{{ myhosts }}' #contains the list of hosts
  gather_facts: no

  tasks:
    - debug:
        var: myhosts
        
    - name: Gather facts
      setup:
        gather_subset: min

    - name: Save the Hostnames
      set_fact:
        hosts_list: "{{ ansible_hostname }}"
   
    - debug:
        var: hosts_list

    - name: Save hostlist into a file
      lineinfile:
        line: "{{ hosts_list }}"
        path: "/tmp/Hosts_1.txt"
      delegate_to: localhost
