---
- name: test users
  hosts: all
  vars:
    tower_host: '{{ lookup("env", "TOWER_HOST") }}'
    tower_username: '{{ lookup("env", "TOWER_USERNAME") }}'
    tower_password: '{{ lookup("env", "TOWER_PASSWORD") }}'
    
  tasks:
    - name: Variables
      shell: export
      register: result
      
    - debug:
        msg: "{{ result }}"
