- hosts: all
  become: yes
  tasks:
  - name: original user
    shell: 'whoami'

  - name: become_user non root
    shell: 'whoami'
    become_user: alfonso  

  - name: become_user root
    shell: 'whoami'
    become_user: root
