- hosts: all
  tasks:
  - name: original user
    shell: 'whoami'

  - name: become_user non root
    become: yes
    become_user: alfonso
    file:
        path: /tmp/alfonso.txt
        state: touch

  - name: become_user root
    shell: 'whoami'
    become: yes
    become_user: root
