---
- name: Test dnf
  hosts: all

  vars:
    ds_packages:
      - "@redhat-ds:11"
      - cockpit-dashboard

  tasks:
    - name: 'Install DS and dependencies' 
      ansible.builtin.package:                
        name: "{{ ds_packages }}"         
        state: latest                     
                                      
    - name: 'Install DS and dependencies 2'
      ansible.builtin.package:                
        name:  
          - "@redhat-ds:11"
          - cockpit
        state: present  
