---
- name: Test dnf
  hosts: all

  vars:
    ds_packages:
      - cockpit-dashboard
      - "@redhat-ds:11"

  tasks:
    - name: 'Install DS and dependencies' 
      ansible.builtin.dnf:                
        name: "{{ ds_packages }}"         
        state: latest                     
                                      
    - name: 'Install DS and dependencies 2'
      ansible.builtin.dnf:                
        name:                             
          - cockpit
          - "@redhat-ds:11"
        state: present  
