- name: schedule launcher
  hosts: all
  become: true
  tasks:
    - name: unarchive test
      ansible.builtin.copy:
        src: /apps/awx/package/test.tar
        dest: /opt/unarchivedb/
        group: root
        owner: root
