- name: Azure
  hosts: all
  tasks:
   - name: Create a snapshot by copying an existing managed disk.
     azure_rm_snapshot:
       resource_group: myResourceGroup
       subscription_id: avewq243t23
       tenant: 123456789
       secret: 123456789
       client_id:  123456789
       cert_validation_mode: ignore
       name: "ansible-{{ snapident }}-{{ (item.split('/')[-1]).split('-')[:7]|join('-')|default(item.split('/')[-1]) }}"
       sku:
         name: Standard_ZRS
       creation_data:
         create_option: Copy
         source_id: '/subscriptions/sub123/resourceGroups/group123/providers/Microsoft.Compute/disks/disk123'
       append_tags: True
       tags:
         test: "test"
