- name: schedule launcher
  hosts: all
  tasks:
    - name: copy files
      ansible.builtin.copy:
        src: /tmp/etc/
        dest: /opt/etc
        mode: "0644"
        directory_mode: "0755"
        remote_src: true
        owner: root
        group: root
