- name: schedule launcher
  hosts: all
  become: true
  tasks:
    - name: Copy a "sudoers" file on the remote machine for editing
      ansible.builtin.copy:
        src: /opt/test/kk.txt
        dest: /opt/test/
