- name: create job template
  hosts: all
  tasks:
    - name: Create Ping job template
      ansible.controller.job_template:
        name: "Ping"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "Demo Project"
        playbook: "03001316.yml"
        verbosity: 4
        credentials:
          - "Local"
        state: "present"
