- name: create job template
  hosts: all
  tasks:
    - name: Survey Template with vars
      controller_configuration:
        name: TEST ALFONSO
        job_type: run
        inventory: Demo Inventory
        execution_environment: Default
        project: Demo Project
        playbook: helloworld.yml
        credentials: Demo Credential
        verbosity: 0
