- name: create job template
  hosts: all
  tasks:
    - name: Create Ping job template
      ansible.controller.job_template:
        name: "Ping"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "Demo Project"
        playbook: "hello_world.yml"
        verbosity: 4
        credentials: "Demo Credential"
        state: "present"
