---
- name: say hello
  hosts: all
  gather_facts: yes
  become: no

  tasks:
    - name: print hello world
      debug:
        msg: "Hello World!"
        verbosity: 0
    - name: Show Host name
      debug:
        var: ansible_hostname
    - name: Test debug with Shortname
      debug:
        msg: "Shortname works"
    - name: Test debug with FQCN
      ansible.builtin.debug:
        msg: "FQCN works}"
