---
- name: Test export import
  hosts: localhost
  gather_facts: false
  environment:
    CONTROLLER_HOST: https://192.168.122.60
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: alfonso123
    CONTROLLER_VERIFY_SSL: false
  tasks:
    - name: Export assets
      ansible.controller.export:
         credential: 'all'
      register: export_output
