---
- name: Testing collection usage
  hosts: all
  strategy : free
  tasks:
    - name: Test debug with Shortname
      debug:
        msg: "Shortname works"
    - name: Test debug with FQCN
      ansible.builtin.debug:
        msg: "FQCN works}"
        
# - name: Test at with FQCN
#   ansible.posix.at:
#     command: ls -d / >/dev/null
#     state: absent
