- name: Collect
  hosts: all
  gather_facts: false
  tasks: 
    - name: collect custom
      become: true
      ansible.builtin.setup:
        filter:
          - ansible_local
        fact_path: /etc/ansible/compliance.d/
