- name: fetch
  hosts: all
  tasks:
    - name: get list of the result files
      find:
        paths: /opt
        patterns: '*02.ods'
        #use_regex: true
      register: file2fetch
    - name: fetch results to localhost
      fetch:
        flat: yes
        src: "/opt/base64.txt"
        dest: "/tmp/"
      with_items: "{{ file2fetch.files }}"
