---
- name: Test mysql
  hosts: all

  tasks:
      - name: Create a new database with name test
        community.mysql.mysql_db:
          name: test
          state: present
          
  vars:
     - ansible_python_interpreter: "{{ansible_playbook_python}}"
