---
- name: Test mysql
  hosts: all

  tasks:
      - name: Create a new database with name test
        community.mysql.mysql_db:
          name: test
          login_host: 192.168.122.44
          state: present
