- name: oracle task
  hosts: all
  tasks:
    - name: List instances in compartment
      oracle.oci.oci_compute_instance_facts:
        compartment_id: 2
      register: instances_list
      delegate_to: localhost
