---
- name: Migrate VMs by request
  hosts: all
  connection: local
  tasks:
    # Migrate VM
    - name: Migrate VM
      redhat.rhv.ovirt_vm:
        state: running
        name: alfonso
        alfonso: true
        migrate: true
        host: 192.168.122.99
        wait_after_lease: 30
     #loop: "{{ vm_name }}"
