---
- name: Migrate VMs by request
  hosts: all
  connection: local
  
  pre_tasks:
    - name: Login to rhev-M
       redhat.rhv.ovirt_auth:
        hostname: "https://alfonso.test.local"
        username: "alfonso"
        password: "alfonso"
      tags:
        - always

  tasks:
    # Migrate VM
    - name: Migrate VM
       redhat.rhv.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: running
        name: "alfonso"
        migrate: true
        host: "192.168.122.99"
        wait_after_lease: 30
     #loop: "{{ vm_name }}"
