---
- name: Migrate VMs by request
  hosts: all
  connection: local
  tasks:
    # Migrate VM
    - name: Migrate VM
      redhat.rhv.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: running
        name: "{{ vm_name }}"
        migrate: true
        host: "{{ hv_destination }}"
        wait_after_lease: 30
     #loop: "{{ vm_name }}"

  post_tasks:
    - name: Logout from rhev-M
      redhat.rhv.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
         - always
