---
- name: Migrate VMs by request
  hosts: all
  connection: local

  vars_files:
    - rhev_vars.yml
    - requirements.yml

  pre_tasks:
    - name: Login to rhev-M
      ovirt_auth:
        hostname: "{{ rhev_fqdn }}"
        username: "{{ rhev_user }}"
        password: "{{ rhev_password }}"
      tags:
        - always

  tasks:

    # Migrate VM
    - name: Migrate VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: running
        name: "{{ vm_name }}"
        migrate: true
        host: "{{ hv_destination }}"
        wait_after_lease: 30
     #loop: "{{ vm_name }}"

  post_tasks:
    - name: Logout from rhev-M
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
         - always
