---
- name: Migrate VMs by request
  hosts: all
  connection: local
  tasks:
    # Migrate VM
    - name: Migrate VM
      redhat.rhv.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: running
        name: "alfonso"
        migrate: true
        host: "192.168.122.99"
        wait_after_lease: 30
        alfonso: true
     #loop: "{{ vm_name }}"
