- name: satellite
  hosts: all
  tasks:
    - name: "Show all content view_versions for a content view"
      redhat.satellite.content_view_version_info:
        organization: "test"
        content_view: "CentOS 8 View"
