- name: satellite
  hosts: all
  tasks:
    - name: "Show all content view_versions for a content view"
      redhat.satellite.content_view_version_info:
        server_url: "https://satellite.example.com"
        organization: "test"
        username: "{{ lookup('env','SATELLITE_USERNAME') }}"
        password: "{{ lookup('env','SATELLITE_PASSWORD') }}"
        content_view: "CentOS 8 View"
