- name: satellite
  hosts: all
  tasks:
    - name: variables
      ansible.builtin.command: env
      register: output
      
    - name: debug
      ansible.builtin.debug:
        var: output
      
    - name: "Create or update Fedora content view"
      redhat.satellite.content_view:
        username: "{{ lookup('env','SATELLITE_USERNAME') }}"
        password: "{{ lookup('env','SATELLITE_PASSWORD') }}"
        server_url: "{{ lookup('env','SATELLITE_SERVER_URL') }}"
        name: "Fedora CV"
        organization: "My Cool new Organization"
        repositories:
         - name: 'Fedora 26'
           product: 'Fedora'
