- name: satellite
  hosts: all
  tasks:
    - name: "Show all content view_versions for a content view"
      redhat.satellite.content_view_version_info:
        server_url: "{{ lookup('env','FOREMAN_SERVER_URL') }}"
        username: "{{ lookup('env','FOREMAN_USERNAME') }}"
        password: "{{ lookup('env','FOREMAN_PASSWORD') }}"
        organization: "test"
        content_view: "CentOS 8 View"
