- name: setup
  hosts: all
  tasks:
    - name: Collect only facts returned by facter
      ansible.builtin.setup:
        gather_subset:
        - '!all'
        - '!any'
        - facter

    - name: Collect only selected facts
      ansible.builtin.setup:
        filter:
        - 'ansible_distribution'
        - 'ansible_machine_id'
        - 'ansible_*_mb'
