- hosts: all
  gather_facts: no
  tasks:
    - name: Read PermitRootLogin from sshd_config
      shell: awk '/^PermitRootLogin/ {print $2}' /etc/ssh/sshd_config
      register: PermitRootLogin
      changed_when: false

    - name: Read PermitEmptyPasswords from sshd_config
      shell: awk '/^PermitEmptyPasswords/ {print $2}' /etc/ssh/sshd_config
      register: PermitEmptyPasswords
      changed_when: false

    - name: Output from sshd_config
      debug: 
        msg: 
          - PermitRootLogin {{ PermitRootLogin.stdout }}
          - PermitEmptyPasswords {{ PermitEmptyPasswords.stdout }}
      failed_when: "'without-password' not in PermitRootLogin.stdout or 'no' not in PermitEmptyPasswords.stdout"
