- name: schedule launcher
  hosts: all
  tasks:
    - name: Create symbolic link
      file:
        src: /tmp/symlink
        dest: /tmp/symlinktest
        owner: alfonso
        group: alfonso
        state: link
