- name: schedule launcher
  hosts: all
  tasks:
    - name: Create symbolic link
      file:
        src: /root/symlink
        dest: /root/symlinktest
        owner: alfonso
        group: alfonso
        state: link
