- name: schedule launcher
  hosts: all
  become_user: alfonso
  become: yes
  tasks:
    - name: Create symbolic link
      file:
        src: /tmp/symlink
        dest: /tmp/symlinktest
        owner: alfonso
        group: alfonso
        state: link
