- name: Install multiple vms
  gather_facts: no
  hosts: localhost
  tasks:

  - name: Create a virtual machine from a template
    vmware.vmware_rest.vcenter_vm:
      vcenter_hostname: vcenter.vmware.gsslab.pnq2.redhat.com
      vcenter_validate_certs: false
      guest_OS: FEDORA
      placement:
         cluster: /my_dc/host/my_cluster
         folder: /AnsibleCreatedVMs
         datacenter: /my_dc/datacenter/my_cluster
      memory:
        hot_add_enabled: true
        size_MiB: 1024
      cpu:
        cores_per_socket: 2
        count: 1
      power_on: true
    delegate_to: localhost
    register: deploy
