---
- name: Capture POSTs from windows event
  hosts: all
  sources:
    - test_xxx:
        a: 'a'
        interval: 60
        xxx_URL: "https://xxx.xxx.xx"
        MAIL: "xxx@xxxx"
        API_TOKEN: "token
