- hosts: localhost

  vars_files:
    - vmware_vars.yml
  tasks:
    - name: Create VM
      vmware_guest:
        cluster: "{{ cluster }}"
        datacenter: "{{ dc }}"
        disk:
        - size_gb: "{{ size }}"
          type: thin
          datastore: autoselect_datastore
        folder: "{{ path }}"
        hardware:
          memory_mb: "{{ mem }}"
          num_cpus: "{{ cpu }}"
          scsi: paravirtual
        name: "{{ vmname }}"
        networks: 
        - name: "{{ network }}"
        state: present
        template: "{{ template_name }}"
        validate_certs: "no"
      register: temp_vm
      
    - name: created vm using template
      debug:
        msg: "created VM using template: {{ temp_vm }}"
