---
- name: Hostname
  hosts: all
  tasks:
     - set_fact:
          name: "{{ ansible_hostname | upper }}"
          osversion: "{{ osversion }}"
       when: ansible_distribution == "{{ version }}"
     - debug:
          msg: "{{ name }} {{ osversion }}"
