---
- name: Hostname
  hosts: all
  become: yes
  tasks:
     - set_fact:
          name: "{{ ansible_hostname | upper }}"
          ip: "{{ ansible_eth0.ipv4.address }}"
       when: ansible_distribution == "{{ version }}"
     - debug:
          msg: "{{ name| default('empty') }} {{ ip | default('empty') }}"
