---
- name: Hostname
  hosts: all
  tasks:
     - set_fact:
          name: "{{ ansible_hostname | upper }}"
       when: ansible_distribution == " version "
     - debug:
          msg: "{{ name }} {{ version }}"
