---
- name: Hostname
  hosts: all
  tasks:
     - set_fact:
          name: "{{ ansible_hostname | upper }}"
          version: "{{ osversion }}"
          hostname: "ansible_distribution"
     - debug:
          msg: "{{ namename }} {{ version }} {{hostname}}"
