---
- name: Hostname
  hosts: all
  tasks:
     - debug:
          msg: "{{ version }}"
     - set_fact:
          name: "{{ ansible_hostname | upper }}"
          ip: "{{ ansible_eth0.ipv4.address }}"
       when: ansible_os_family==  "RedHat"
     - debug:
          msg: "{{ name }} {{ ip }}"
