- name: Load manifest into variable
  local_action:
    module: slurp
    src: /root/manifest/manifest_Subscription_Tower_20210721T064551Z.zip
  register: manifest_file

- name: Post manifest file
  uri:
    url: https://192.168.122.2/api/v2/config/
    method: POST
    user: admin
    password: alfonso123
    body: '{ "eula_accepted": true, "manifest": "{{ manifest_file.content }}" }'
    body_format: json
    validate_certs: false
    force_basic_auth: true
