---
- hosts: all
  tasks:
    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/Alffernandez/private_test.git
        dest: /tmp
        single_branch: yes
        version: main
