---
- name: testing variable stuff
  hosts: all

  tasks:
  - name: get date on the server
    shell: date
    register: output
    
  - name: Sleep for 300 seconds and continue with play
    ansible.builtin.wait_for:
      timeout: 300
    delegate_to: localhost

  - debug: msg="the date is {{output.stdout}}"

  - debug: var=ansible_distribution_version

  - name: group some machines together temporarily
    group_by: key=rhel_{{ansible_distribution_version}}
    register: group_result

  - debug: var=group_result
