- hosts: all
  gather_facts: false
  tasks:
    - name: Add tags to a virtual machine
      community.vmware.vmware_tag_manager:
        hostname: 192.168.122.111
        username: admin
        password: test123
        tag_names:
          - Sample_Tag_0002
          - Category_0001:Sample_Tag_0003
        object_name: Fedora_VM
        object_type: VirtualMachine
        state: add
      delegate_to: localhost
