- hosts: all
  gather_facts: false
  tasks:
    - name: Create a tag
      community.vmware.vmware_tag:
        hostname: 192.168.122.11
        username: admin
        password: test123
        category_id: 'urn:vmomi:InventoryServiceCategory:e785088d-6981-4b1c-9fb8-1100c3e1f742:GLOBAL'
        tag_name: Sample_Tag_0002
        tag_description: Sample Description
        state: present
      delegate_to: localhost
